#Project Setup
general:
  productiveBranch: 'master'

#Steps Specific Configuration
steps:
  executeMaven:
#    dockerImage: 'maven:3.2-jdk-8-onbuild'
    globalSettingsFile: ''
    projectSettingsFile : 'settings.xml'

#Stage Specific Configurations
stages:
  staticCodeChecks:
    findbugsExcludesFile: '' #Path to findbugs exclude file
    pmdExcludes: '' # List or ANT style patterns

#  integrationTests:
#    crendentials:
#      - alias: ''
#        credentialId: ''

#  s4SdkQualityChecks:
#    jacocoExcludes:
#      - ''
#    nonErpDestinations:
#      - ''

#  productionDeployment:
#    neoTargets:
#      - host: 'host'
#        account: 'yourAccount'
#        application: 'appName'
#        credentialsId: 'credentialsId'
